update RNA pipeline
molgenis/NGS_RNA pull request #27
Opened 2021-03-03 10:21 UTC by Gerbenvandervries

2021-03-03 11:14 UTC, marieke-bijlsma requested changes, later dismissed
See inline comments

2021-03-03 11:14 UTC, marieke-bijlsma commented on parameters.csv
> +gatkJar,GenomeAnalysisTK.jar
2x dezelfde parameter?

2021-03-03 11:14 UTC, marieke-bijlsma commented on parameters.homo_sapiens.csv
> +indexSpecies, /apps/data/Ensembl/GrCh37.75/pub/release-75/fasta/homo_sapiens/${indexFileID}
Kun je hier niet ${dataDir} gebruiken i.p.v. /apps/data/?

2021-03-03 11:14 UTC, marieke-bijlsma commented on protocols/CopyToResultsDir.sh
> +	cp "${intermediateDir}"/*.counts.txt "${projectResultsDir}"/expression/perSampleExpression
Bij veel van de paden eindigen de dubbele quotes na de variabele, klopt dit? 
Dus waarom "${projectResultsDir}"/expression/perSampleExpression i.p.v. "${projectResultsDir}/expression/perSampleExpression"

2021-03-03 11:14 UTC, marieke-bijlsma commented on protocols/CopyToResultsDir.sh
> +distinced groups within the samples.
Bedoel je distinct?

2021-03-03 11:14 UTC, marieke-bijlsma commented on protocols/HTSeq_count.sh
> +STRANDED="$(num1="$(tail -n 2 "${strandedness}" | awk '{print $7'} | head -n 1)"; num2="$(tail -n 2 "${strandedness}" | awk '{print $7'} | tail -n 1)"; if (( $(echo "$num1 > 0.6" | bc -l) )); then ec
Ik denk dat de enkele quote na de } moet komen.

2021-03-04 11:26 UTC, RoanKanninga approved these changes

2021-03-04 11:26 UTC, merged